from __future__ import annotations

import unittest

import pandas as pd

from sourcing.network_access import (
    build_access_summary,
    build_alias_index,
    deduplicate_connections,
    match_linkedin_connections,
    parse_linkedin_csv,
)


class NetworkAccessTests(unittest.TestCase):
    def test_linkedin_notes_preamble_is_ignored(self) -> None:
        raw = (
            b"Notes:\nExport generated by LinkedIn\n"
            b"First Name,Last Name,URL,Email Address,Company,Position,Connected On\n"
            b"Ada,Lovelace,https://linkedin.example/ada,,Example AG,Treasury Manager,01 Jan 2026\n"
        )
        frame = parse_linkedin_csv(raw)
        self.assertEqual(len(frame), 1)
        self.assertEqual(frame.iloc[0]["Company"], "Example AG")

    def test_unique_explicit_alias_matches(self) -> None:
        universe = pd.DataFrame([{
            "canonical_company_id": "example",
            "company": "Example Group AG",
            "aliases_entities": "Example; Example Group",
        }])
        index = build_alias_index([universe])
        raw = pd.DataFrame([{
            "First Name": "Ada", "Last Name": "Lovelace", "Company": "Example",
            "Position": "Treasury Manager", "URL": "https://linkedin.example/ada",
        }])
        matched = match_linkedin_connections(raw, index, added_at="2026-08-25T00:00:00+00:00")
        self.assertEqual(matched.iloc[0]["canonical_company_id"], "example")
        self.assertEqual(matched.iloc[0]["company_match_status"], "matched_exact_alias")

    def test_ambiguous_alias_is_not_silently_assigned(self) -> None:
        universes = [pd.DataFrame([
            {"canonical_company_id": "alpha-1", "company": "Alpha Holdings", "aliases_entities": "Alpha"},
            {"canonical_company_id": "alpha-2", "company": "Alpha Bank", "aliases_entities": "Alpha"},
        ])]
        index = build_alias_index(universes)
        raw = pd.DataFrame([{"First Name": "A", "Last Name": "B", "Company": "Alpha"}])
        matched = match_linkedin_connections(raw, index, added_at="2026-08-25T00:00:00+00:00")
        self.assertEqual(matched.iloc[0]["canonical_company_id"], "")
        self.assertEqual(matched.iloc[0]["company_match_status"], "ambiguous_alias")

    def test_unmatched_company_remains_unmatched_no_fuzzy_guess(self) -> None:
        universe = pd.DataFrame([{
            "canonical_company_id": "example",
            "company": "Example Group AG",
            "aliases_entities": "Example Group",
        }])
        index = build_alias_index([universe])
        raw = pd.DataFrame([{"First Name": "A", "Last Name": "B", "Company": "Example Advisory"}])
        matched = match_linkedin_connections(raw, index, added_at="2026-08-25T00:00:00+00:00")
        self.assertEqual(matched.iloc[0]["canonical_company_id"], "")
        self.assertEqual(matched.iloc[0]["company_match_status"], "unmatched_company")

    def test_reupload_updates_same_linkedin_person(self) -> None:
        existing = pd.DataFrame([{
            "full_name": "Ada Lovelace", "company_raw": "Old Co", "linkedin_url": "https://linkedin.example/ada",
            "position": "Analyst", "company_match_status": "unmatched_company",
        }])
        incoming = pd.DataFrame([{
            "full_name": "Ada Lovelace", "company_raw": "New Co", "linkedin_url": "https://linkedin.example/ada",
            "position": "Manager", "company_match_status": "unmatched_company",
        }])
        combined = deduplicate_connections(existing, incoming)
        self.assertEqual(len(combined), 1)
        self.assertEqual(combined.iloc[0]["company_raw"], "New Co")
        self.assertEqual(combined.iloc[0]["position"], "Manager")

    def test_access_summary_is_factual_only(self) -> None:
        connections = pd.DataFrame([
            {
                "full_name": "A", "canonical_company_id": "x", "matched_company": "X",
                "company_match_status": "matched_exact_alias", "position": "Treasury Manager",
            },
            {
                "full_name": "B", "canonical_company_id": "x", "matched_company": "X",
                "company_match_status": "matched_exact_alias", "position": "Investment Analyst",
            },
            {
                "full_name": "C", "canonical_company_id": "", "matched_company": "",
                "company_match_status": "ambiguous_alias", "position": "CFO",
            },
        ])
        summary = build_access_summary(connections)
        self.assertEqual(len(summary), 1)
        self.assertEqual(int(summary.iloc[0]["contact_count"]), 2)
        self.assertTrue(bool(summary.iloc[0]["has_access"]))
        self.assertNotIn("rating", summary.columns)
        self.assertNotIn("score", summary.columns)


if __name__ == "__main__":
    unittest.main()
